// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("BinaryRage")]
[assembly: AssemblyDescriptionAttribute("BinaryRage")]
[assembly: GuidAttribute("191D893F-7087-4E59-9AEE-5FEF4172E3FC")]
[assembly: AssemblyProductAttribute("BinaryRage")]
[assembly: AssemblyVersionAttribute("1.4.0.0")]
[assembly: AssemblyFileVersionAttribute("1.4.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.4.0.0";
    }
}
